create table lkup_cd_bases ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_battedball ( value_cd varchar(1), shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_event ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_fld ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_h ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_hand ( value_cd varchar(1), shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_park_daynight ( value_cd varchar(1), shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_park_field ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_park_precip ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_park_sky ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_park_wind_direction( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_recorder_method ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_cd_recorder_pitches ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_id_base ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_id_home ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_id_last ( value_cd integer, shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_id_park ( value_cd varchar(8), shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_id_player ( value_cd varchar(8), shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_id_recorder ( value_cd varchar(8), shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_id_team ( value_cd varchar(8), shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

create table lkup_id_ump ( value_cd varchar(8), shortname_tx varchar(8), longname_tx varchar(30), description_tx varchar(255));

INSERT INTO LKUP_CD_BASES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (0, '___', 'Empty', NULL);

INSERT INTO LKUP_CD_BASES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, '1__', '1B only', NULL);

INSERT INTO LKUP_CD_BASES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, '_2_', '2B only', NULL);

INSERT INTO LKUP_CD_BASES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (3, '12_', '1B 2B', NULL);

INSERT INTO LKUP_CD_BASES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (4, '__3', '3B only', NULL);

INSERT INTO LKUP_CD_BASES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (5, '1_3', '1B 3B', NULL);

INSERT INTO LKUP_CD_BASES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (6, '_23', '2B 3B', NULL);

INSERT INTO LKUP_CD_BASES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (7, '123', 'Loaded', NULL);

INSERT INTO LKUP_CD_BATTEDBALL (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES ('F', 'FB', 'Fly Ball', NULL);

INSERT INTO LKUP_CD_BATTEDBALL (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES ('G', 'GB', 'Ground Ball', NULL);

INSERT INTO LKUP_CD_BATTEDBALL (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES ('L', 'LD', 'Line Drive', NULL);

INSERT INTO LKUP_CD_BATTEDBALL (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES ('P', 'PU', 'Pop Up', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, 'Out', 'Generic Out', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (3, 'K', 'Strikeout', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (4, 'SB', 'Stolen Base', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (5, 'DI', 'Defensive Indifference', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (6, 'CS', 'Caught Stealing', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (8, 'PK', 'Pickoff', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (9, 'WP', 'Wild Pitch', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (10, 'PB', 'Passed Ball', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (11, 'BK', 'Balk', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (12, 'OA', 'Other Advance', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (13, 'FE', 'Foul Error', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (14, 'NIBB', 'Nonintentional Walk', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (15, 'IBB', 'Intentional Walk', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (16, 'HBP', 'Hit By Pitch', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (17, 'XI', 'Interference', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (18, 'ROE', 'Error', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (19, 'FC', 'Fielder Choice', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (20, '1B', 'Single', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (21, '2B', 'Double', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (22, '3B', 'Triple', NULL);

INSERT INTO LKUP_CD_EVENT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (23, 'HR', 'Homerun', NULL);

INSERT INTO LKUP_CD_FLD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, 'P', 'Pitcher', NULL);

INSERT INTO LKUP_CD_FLD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, 'C', 'Catcher', NULL);

INSERT INTO LKUP_CD_FLD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (3, '1B', 'Firstbase', NULL);

INSERT INTO LKUP_CD_FLD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (4, '2B', 'Secondbase', NULL);

INSERT INTO LKUP_CD_FLD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (5, '3B', 'Thirdbase', NULL);

INSERT INTO LKUP_CD_FLD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (6, 'SS', 'Shortstop', NULL);

INSERT INTO LKUP_CD_FLD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (7, 'LF', 'Leftfield', NULL);

INSERT INTO LKUP_CD_FLD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (8, 'CF', 'Centerfield', NULL);

INSERT INTO LKUP_CD_FLD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (9, 'RF', 'Rightfield', NULL);

INSERT INTO LKUP_CD_H (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, '1B', 'Single', NULL);

INSERT INTO LKUP_CD_H (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, '2B', 'Double', NULL); 

INSERT INTO LKUP_CD_H (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (3, '3B', 'Triple', NULL);

INSERT INTO LKUP_CD_H (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (4, 'HR', 'Homerun', NULL);

INSERT INTO LKUP_CD_HAND (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES ('?', NULL, 'Unknown', NULL);

INSERT INTO LKUP_CD_HAND (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES ('F', NULL, 'Unknown', NULL);

INSERT INTO LKUP_CD_HAND (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES ('L', 'LH', 'Lefthanded', NULL);

INSERT INTO LKUP_CD_HAND (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES ('R', 'RH', 'Righthanded', NULL);

INSERT INTO LKUP_CD_PARK_DAYNIGHT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES ('D', 'D', 'Day', NULL);

INSERT INTO LKUP_CD_PARK_DAYNIGHT (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES ('N', 'N', 'Night', NULL);

INSERT INTO LKUP_CD_PARK_FIELD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (0, 'Unknown', 'Unknown', NULL);

INSERT INTO LKUP_CD_PARK_FIELD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, 'Soaked', 'Soaked', NULL);

INSERT INTO LKUP_CD_PARK_FIELD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, 'Wet', 'Wet', NULL);

INSERT INTO LKUP_CD_PARK_FIELD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (3, 'Damp', 'Damp', NULL);

INSERT INTO LKUP_CD_PARK_FIELD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (4, 'Dry', 'Dry', NULL);

INSERT INTO LKUP_CD_PARK_PRECIP (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (0, 'Unknown', 'Unknown', NULL);

INSERT INTO LKUP_CD_PARK_PRECIP (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, 'None', 'None', NULL);

INSERT INTO LKUP_CD_PARK_PRECIP (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, 'Drizzle', 'Drizzle', NULL);

INSERT INTO LKUP_CD_PARK_PRECIP (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (3, 'Showers', 'Showers', NULL);

INSERT INTO LKUP_CD_PARK_PRECIP (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (4, 'Rain', 'Rain', NULL);

INSERT INTO LKUP_CD_PARK_PRECIP (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (5, 'Snow', 'Snow', NULL);

INSERT INTO LKUP_CD_PARK_SKY (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (0, 'Unknown', 'Unknown', NULL);

INSERT INTO LKUP_CD_PARK_SKY (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, 'Sunny', 'Sunny', NULL);

INSERT INTO LKUP_CD_PARK_SKY (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, 'Cloudy', 'Cloudy', NULL);

INSERT INTO LKUP_CD_PARK_SKY (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (3, 'Overcast', 'Overcast', NULL);

INSERT INTO LKUP_CD_PARK_SKY (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (4, 'Night', 'Night', NULL);

INSERT INTO LKUP_CD_PARK_SKY (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (5, 'Dome', 'Dome', NULL);

INSERT INTO LKUP_CD_PARK_WIND_DIRECTION (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (0, 'Unknown', 'Unknown', NULL);

INSERT INTO LKUP_CD_PARK_WIND_DIRECTION (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, 'tolf', 'To LF', NULL);

INSERT INTO LKUP_CD_PARK_WIND_DIRECTION (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, 'tocf', 'To CF', NULL);

INSERT INTO LKUP_CD_PARK_WIND_DIRECTION (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (3, 'torf', 'To RF', NULL);

INSERT INTO LKUP_CD_PARK_WIND_DIRECTION (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (4, 'ltor', 'LF to RF', NULL);

INSERT INTO LKUP_CD_PARK_WIND_DIRECTION (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (5, 'fromlf', 'From LF', NULL);

INSERT INTO LKUP_CD_PARK_WIND_DIRECTION (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (6, 'fromcf', 'From CF', NULL);

INSERT INTO LKUP_CD_PARK_WIND_DIRECTION (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (7, 'fromrf', 'From RF', NULL);

INSERT INTO LKUP_CD_PARK_WIND_DIRECTION (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (8, 'rtol', 'RF to LF', NULL);

INSERT INTO LKUP_CD_RECORDER_METHOD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (0, 'Unknown', 'Unknown', NULL);

INSERT INTO LKUP_CD_RECORDER_METHOD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, 'Park', 'Park', NULL);

INSERT INTO LKUP_CD_RECORDER_METHOD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, 'TV', 'TV', NULL);

INSERT INTO LKUP_CD_RECORDER_METHOD (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (3, 'Radio', 'Radio', NULL);

INSERT INTO LKUP_CD_RECORDER_PITCHES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (0, 'Unknown', 'Unknown', NULL);

INSERT INTO LKUP_CD_RECORDER_PITCHES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, 'Pitches', 'Pitches', NULL);

INSERT INTO LKUP_CD_RECORDER_PITCHES (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, 'Count', 'Count', NULL);

INSERT INTO LKUP_ID_BASE (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (0, 'None', 'None', NULL);

INSERT INTO LKUP_ID_BASE (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, '1B', 'Firstbase', NULL);

INSERT INTO LKUP_ID_BASE (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (2, '2B', 'Secondbase', NULL);

INSERT INTO LKUP_ID_BASE (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (3, '3B', 'Thirdbase', NULL);

INSERT INTO LKUP_ID_BASE (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (4, 'ER', 'Earned Run', NULL);

INSERT INTO LKUP_ID_BASE (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (5, 'UER', 'Unearned Run', NULL);

INSERT INTO LKUP_ID_BASE (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (6, 'TUER', 'Team Unearned Run', NULL);

INSERT INTO LKUP_ID_HOME (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (0, 'A', 'Away', NULL);

INSERT INTO LKUP_ID_HOME (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, 'H', 'Home', NULL);

INSERT INTO LKUP_ID_LAST (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (0, 'F', 'First', NULL);
INSERT INTO LKUP_ID_LAST (VALUE_CD, SHORTNAME_TX, LONGNAME_TX, DESCRIPTION_TX) VALUES (1, 'L', 'Last', NULL);

